// Subscription billing helpers shared by the admin pages and the owner's
// Paramètres → Abonnement section. Rows come from the subscriptions /
// subscription_invoices / subscription_payments tables (see
// supabase/migration_subscriptions.sql — invoices are generated by pg_cron on
// the 1st of each month).

export interface SubscriptionRow {
  id: string;
  practice_id: string;
  plan: string;
  monthly_price: number;
  currency: string;
  trial_ends_at: string;   // YYYY-MM-DD
  status: "trial" | "active" | "cancelled";
  cancelled_at: string | null;
  created_at: string;
}

export interface SubscriptionInvoiceRow {
  id: string;
  practice_id: string;
  number: string;
  period_start: string;    // YYYY-MM-DD
  period_end: string;
  issued_at: string;
  plan: string;
  amount: number;
  previous_balance: number; // >0 owed, <0 credit (before this invoice)
  total_due: number;        // previous_balance + amount
  currency: string;
}

export interface SubscriptionPaymentRow {
  id: string;
  practice_id: string;
  amount: number;
  paid_at: string;
  method: "virement" | "especes" | "cheque" | "carte" | "autre";
  note: string | null;
}

export const PAYMENT_METHODS = ["virement", "especes", "cheque", "carte", "autre"] as const;

/** Current balance: everything invoiced minus everything paid (>0 owed, <0 credit). */
export function currentBalance(invoices: Pick<SubscriptionInvoiceRow, "amount">[], payments: Pick<SubscriptionPaymentRow, "amount">[]): number {
  const billed = invoices.reduce((s, i) => s + Number(i.amount), 0);
  const paid = payments.reduce((s, p) => s + Number(p.amount), 0);
  return Math.round((billed - paid) * 100) / 100;
}

/** Status shown to people: a "trial" row whose trial is over reads as active. */
export function effectiveStatus(sub: Pick<SubscriptionRow, "status" | "trial_ends_at">, today = new Date().toISOString().slice(0, 10)): "trial" | "active" | "cancelled" {
  if (sub.status === "cancelled") return "cancelled";
  return sub.trial_ends_at > today ? "trial" : "active";
}

/** "YYYY-MM-DD" → localized "septembre 2026" (UTC-noon anchor, no timezone drift). */
export function monthLabel(date: string, locale = "fr"): string {
  return new Date(`${date.slice(0, 10)}T12:00:00Z`).toLocaleDateString(locale, { month: "long", year: "numeric", timeZone: "UTC" });
}

export function fmtDay(date: string, locale = "fr"): string {
  return new Date(`${date.slice(0, 10)}T12:00:00Z`).toLocaleDateString(locale, { day: "2-digit", month: "2-digit", year: "numeric", timeZone: "UTC" });
}

export function fmtMoney(v: number, currency = "MAD"): string {
  return `${Number(v).toFixed(2).replace(".", ",")} ${currency}`;
}
